### ISSUE TITLE
Missing distorm3 library

### ISSUE THREAD

**Issue by petiepooo** [blacktop/docker-volatility#2]
For instance, when running the mbrparser plugin, I get the following output:
Volatility Foundation Volatility Framework 2.3.1
ERROR   : volatility.plugins.mbrparser: Install distorm3 code.google.com/p/distorm/

**Comment by blacktop** [comment]
There...can I go to sleep now?!

**Comment by blacktop** [comment]
:wink:

**Comment by petiepooo** [comment]
LOL!  Yes, you can return to your slumber.

Seriously, though.. if I didn't say it before, thanks!  Rolling up volatility and all its dependencies into a docker image makes it easy to deploy and use without needing to "pollute" the host with all these other packages.  It makes my life easier.

If other things do come up, I'm hoping to write more pull requests rather than issues, as I know that makes your life easier...

And again, Thanks!
