### ISSUE TITLE
Missing dependencies for plugins

### ISSUE THREAD

**Issue by morallo** [blacktop/docker-volatility#4]
Currently, the `plugins` tag fails to run volatility:
```
$ docker run --rm -v $(pwd):/data:ro blacktop/volatility:plugins --plugins=/plugins --info                                                   

Volatility Foundation Volatility Framework 2.6
*** Failed to import volatility.plugins.community.YingLi.python_strings (ImportError: No module named YingLi.python_strings)
ERROR   : volatility.debug    : Please install DPAPIck library: https://bitbucket.org/jmichel/dpapick
*** Failed to import volatility.plugins.community.StanislasLejay.linux.get_profile (ImportError: No module named linux.get_profile)
*** Failed to import volatility.plugins.community.FrancescoPicasso.mimikatz (AttributeError: 'module' object has no attribute 'ULInt32')
*** Failed to import volatility.plugins.community.AlexanderTarasenko.windbg (ImportError: No module named pykd)
*** Failed to import volatility.plugins.community.TranVienHa.osint (ImportError: No module named socks)
```

I guess as the Community repository evolves, new dependencies are added.

You need to hardcode a tag/commit in the Dockerfile to make sure you install all the dependencies in the build. I will try to create a PR.

Thx for the work maintaining this :-)

**Comment by morallo** [comment]
I can't test now, but I don't think it solves it. The plugin directories don't include their dependencies as subrepos (example: [this](https://github.com/volatilityfoundation/community/tree/master/TranVienHa) has non included [requirements](https://github.com/tranvienha/volatility-osint#requirements))

New python packages should be installed for specific plugins through `apt` or `pip`. As you don't know what future dependencies will be added, you need to "freeze" the version of the Community repo that you install to ensure the automated build will work.

**Comment by blacktop** [comment]
Sounds like volatility community repo should add that as a requirement for plugins :(. The folders I quickly looked at had no requirements files

**Comment by blacktop** [comment]
If you do get some extra time it might also be cool to decide which plugins make sense to install and which ones do not. for example. `windbg` might only make sense on Windows. 

I am also confused by the error output:

```
Volatility Foundation Volatility Framework 2.6
*** Failed to import volatility.plugins.community.YingLi.python_strings (ImportError: No module named YingLi.python_strings)
ERROR   : volatility.debug    : Please install DPAPIck library: https://bitbucket.org/jmichel/dpapick
*** Failed to import volatility.plugins.community.StanislasLejay.linux.get_profile (ImportError: No module named linux.get_profile)
*** Failed to import volatility.plugins.community.FrancescoPicasso.mimikatz (AttributeError: 'module' object has no attribute 'ULInt32')
*** Failed to import volatility.plugins.community.AlexanderTarasenko.windbg (ImportError: No module named pykd)
*** Failed to import volatility.plugins.community.TranVienHa.osint (ImportError: No module named socks)
make: *** [test] Error 1
```
 
Isn't `linux.get_profile` a part of volatility proper?

**Comment by morallo** [comment]
> If you do get some extra time it might also be cool to decide which plugins make sense to install and which ones do not. for example. windbg might only make sense on Windows.

I would have thought it was useful in Linux too, maybe to analyze dump files, but apparently uses a module which is only available for Windows (`pykd`).

**Comment by morallo** [comment]
I added the missing python packages in #7 

Also, I found the cause of the confusing errors you mentioned in https://github.com/blacktop/docker-volatility/issues/4#issuecomment-277532506.

It's a problem with the Volatility Community repo, I reported it upstream and implemented some dirty hotfixes in the mean time.

All in all, this could get broken again once the Community repo is updated with new dependencies. Would you be ok with "freezing" the commit used to prevent this?

**Comment by blacktop** [comment]
I pinned the commit for the community plugins in my last fix.  Please let me know if/when volatility fixes your issues and then I can unpin the commit?  Probably should just leave it pinned until volatility standardizes they way they do/integrate plugins a little more? :(
