### ISSUE TITLE
Add contrib/plugins to the plugins build

### ISSUE THREAD

**Issue by morallo** [blacktop/docker-volatility#5]
The plugins in volatility/contrib/plugins are not enabled by default in volatility.

They are not included in the enabled plugins. The easiest way would be for them to be copied to /plugins

**Comment by blacktop** [comment]
that is really weird that when you link in a plugin folder that it doesn't know how to reference what is in contrib/plugins ??

**Comment by blacktop** [comment]
your other issue was auto closed from the commit message in my last push, did it actually solve the issue or does it still exist?

**Comment by blacktop** [comment]
also does it solve this one?

**Comment by morallo** [comment]
> The plugins in volatility/contrib/plugins are not enabled by default in volatility.

Check my comment in the pull request https://github.com/blacktop/docker-volatility/pull/6#issuecomment-277526787
