### ISSUE TITLE
Failed to import community plugins

### ISSUE THREAD

**Issue by nov3mb3r** [blacktop/docker-volatility#8]
Upon running the following error appears
`*** Failed to import volatility.plugins.community.LoïcJaquemet.vol_haystack (ImportError: cannot import name api)`

**Comment by blacktop** [comment]
Can you tell me the exact cmd you used?  There is a `plugin` tag that should include all the main plugins and their deps.

**Comment by nov3mb3r** [comment]
`sudo docker run --rm -v /$(pwd):/data:ro blacktop/volatility:plugins -f case01.img imageinfo`

**Comment by blacktop** [comment]
hmmm, that's strange.  I have rebuilt using all the required pip deps and it still errors out.  I think the haystack lib has changed and broken their vol plugin.

**Comment by blacktop** [comment]
pinned haystack to version 0.36 and it seems to be working now

**Comment by blacktop** [comment]
It should be done building in the dockerHUB, so if you did a fresh `docker pull` it should be working now.
